version: '3.9'

services:
  gateway001:
    build:
      context: ./
      dockerfile: DockerFileLiveComments.dev
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      QUEUE: "gateway001"
      RABBIT_MQ: "amqp://guest:guest@rabbitmq:5672/"
    entrypoint: sh -c './liveComments gateway'

  dispatcher001:
    build:
      context: ./
      dockerfile: DockerFileLiveComments.dev
    ports:
      - "8081:8081"
    environment:
      PORT: "8081"
      RABBIT_MQ: "amqp://guest:guest@rabbitmq:5672/"
      QUEUES: "gateway001"
    entrypoint: sh -c './liveComments dispatcher'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
